INSERT INTO Groups VALUES('Age 0-0','500')
INSERT INTO Groups VALUES('Age 0-2','500')
INSERT INTO Groups VALUES('Age 3-5','500')
INSERT INTO Groups VALUES('Age 6-8','800')
INSERT INTO Groups VALUES('Age 9-11','800')
INSERT INTO Groups VALUES('Age 12-14','800')
INSERT INTO AccNanny VALUES('nanny','nanny')
INSERT INTO Nanny VALUES('Lena','Viet Nam',1234,200,8)
INSERT INTO Nanny VALUES('Anna','U.K',1234,400,8)
INSERT INTO Nanny VALUES('Mandy more','U.S',734,200,8)
INSERT INTO Nanny VALUES('Rafica','Indian',434,600,8)
INSERT INTO Doctor VALUES('dr Alonso')
INSERT INTO Doctor VALUES('dr Terry')
INSERT INTO Doctor VALUES('dr Henry')
INSERT INTO Doctor VALUES('dr Fabregas')
INSERT INTO Children VALUES('Sophia','Anna','Tomato','February/2/1996','Anna Frank',1234,1234,'frankfamily@gmail.com','Alice','dr Alonso','Lena','Age 12-14')
INSERT INTO Children VALUES('Lillbo','Ronaldo','Marcel','February/5/1997','Anna Frank',1234,1234,'home@gmail.com','Moraton','dr Henry','Anna','Age 12-14')

