/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main.java
 *
 * Created on Nov 19, 2011, 7:27:18 AM
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class Main extends javax.swing.JFrame {

    private String username;
    private String password;

    /** Creates new form Main */
    public Main(String username, String password) {
        this.username = username;
        this.password = password;
        initComponents();
        this.lblOnline.setText(username + " dang online!");
    }

    public void logOff() {
        menuQuanLyTaiKhoan.setEnabled(false);
        menuChild.setEnabled(false);
        menuClass.setEnabled(false);
        menuNanny.setEnabled(false);
        menuAction.setEnabled(false);
        menuAge.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblWallpaper = new javax.swing.JLabel();
        lblOnline = new javax.swing.JLabel();
        lblPiconline = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuUser = new javax.swing.JMenu();
        menuQuanLyTaiKhoan = new javax.swing.JMenuItem();
        menuDangNhap = new javax.swing.JMenuItem();
        menuDangXuat = new javax.swing.JMenuItem();
        menuThoat = new javax.swing.JMenuItem();
        menuChild = new javax.swing.JMenu();
        menuitemAddchild = new javax.swing.JMenuItem();
        menuNanny = new javax.swing.JMenu();
        menuitemQuanLyBaoMau = new javax.swing.JMenuItem();
        menuClass = new javax.swing.JMenu();
        menuitemAddClass = new javax.swing.JMenuItem();
        menuitemEditClass = new javax.swing.JMenuItem();
        menuitemDeleteClass = new javax.swing.JMenuItem();
        menuitemShowClass = new javax.swing.JMenuItem();
        menuAge = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        menuAction = new javax.swing.JMenu();
        menuitemAddActive = new javax.swing.JMenuItem();
        menuitemEditActive = new javax.swing.JMenuItem();
        menuitemDeleteActive = new javax.swing.JMenuItem();
        menuitemShowActive = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblOnline.setFont(new java.awt.Font("Tahoma", 0, 14));
        lblOnline.setForeground(new java.awt.Color(255, 0, 0));

        lblPiconline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/online.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(lblWallpaper))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPiconline, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(490, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWallpaper)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPiconline)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );

        menuUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/User.png"))); // NOI18N
        menuUser.setText("Quản lý người dùng");

        menuQuanLyTaiKhoan.setText("Quản lý tài khoản");
        menuQuanLyTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyTaiKhoanActionPerformed(evt);
            }
        });
        menuUser.add(menuQuanLyTaiKhoan);

        menuDangNhap.setText("Đăng nhập");
        menuDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDangNhapActionPerformed(evt);
            }
        });
        menuUser.add(menuDangNhap);

        menuDangXuat.setText("Đăng xuất");
        menuDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDangXuatActionPerformed(evt);
            }
        });
        menuUser.add(menuDangXuat);

        menuThoat.setText("Thoát");
        menuThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThoatActionPerformed(evt);
            }
        });
        menuUser.add(menuThoat);

        jMenuBar1.add(menuUser);

        menuChild.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.png"))); // NOI18N
        menuChild.setText("Quản lý trẻ");

        menuitemAddchild.setText("Quản lý trẻ");
        menuitemAddchild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemAddchildActionPerformed(evt);
            }
        });
        menuChild.add(menuitemAddchild);

        jMenuBar1.add(menuChild);

        menuNanny.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nanny.png"))); // NOI18N
        menuNanny.setText("Quản lý bảo mẫu");

        menuitemQuanLyBaoMau.setText("Quản lý bảo mẫu");
        menuitemQuanLyBaoMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemQuanLyBaoMauActionPerformed(evt);
            }
        });
        menuNanny.add(menuitemQuanLyBaoMau);

        jMenuBar1.add(menuNanny);

        menuClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Class.png"))); // NOI18N
        menuClass.setText("Quản lý lớp");

        menuitemAddClass.setText("Thêm lớp học");
        menuClass.add(menuitemAddClass);

        menuitemEditClass.setText("Sửa thông tin lớp học");
        menuClass.add(menuitemEditClass);

        menuitemDeleteClass.setText("Xóa lớp học");
        menuClass.add(menuitemDeleteClass);

        menuitemShowClass.setText("Hiển thị thông tin");
        menuClass.add(menuitemShowClass);

        jMenuBar1.add(menuClass);

        menuAge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.png"))); // NOI18N
        menuAge.setText("Quản lý độ tuổi");
        menuAge.add(jMenuItem11);

        jMenuItem12.setText("jMenuItem12");
        menuAge.add(jMenuItem12);

        jMenuItem13.setText("jMenuItem13");
        menuAge.add(jMenuItem13);

        jMenuItem14.setText("jMenuItem14");
        menuAge.add(jMenuItem14);

        jMenuBar1.add(menuAge);

        menuAction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Modify.png"))); // NOI18N
        menuAction.setText("Quản lý hoạt động của trẻ");

        menuitemAddActive.setText("Thêm hoạt động");
        menuAction.add(menuitemAddActive);

        menuitemEditActive.setText("Sửa thông tin các hoạt động");
        menuAction.add(menuitemEditActive);

        menuitemDeleteActive.setText("Xóa thông tin hoạt động");
        menuAction.add(menuitemDeleteActive);

        menuitemShowActive.setText("Hiển thị thông tin hoạt động");
        menuAction.add(menuitemShowActive);

        jMenuBar1.add(menuAction);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-806)/2, (screenSize.height-356)/2, 806, 356);
    }// </editor-fold>//GEN-END:initComponents

    private void menuQuanLyTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyTaiKhoanActionPerformed
        // TODO add your handling code here:
        FrmQuanLyTaiKhoan frmquanlytaikhoan = new FrmQuanLyTaiKhoan();
        frmquanlytaikhoan.setVisible(true);

    }//GEN-LAST:event_menuQuanLyTaiKhoanActionPerformed

    private void menuDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDangXuatActionPerformed
        // TODO add your handling code here:
        logOff();

    }//GEN-LAST:event_menuDangXuatActionPerformed

    private void menuThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThoatActionPerformed
        // TODO add your handling code here:
        //System.exit(0);
        int choice = JOptionPane.showConfirmDialog(this, "Are you exit?", "Exit",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (choice == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_menuThoatActionPerformed

    private void menuDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDangNhapActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_menuDangNhapActionPerformed

    private void menuitemAddchildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemAddchildActionPerformed
        // TODO add your handling code here:
        FrmQuanLyTre frmquanlytre = new FrmQuanLyTre();
        frmquanlytre.setVisible(true);
    }//GEN-LAST:event_menuitemAddchildActionPerformed

private void menuitemQuanLyBaoMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemQuanLyBaoMauActionPerformed
// TODO add your handling code here:
    FrmQuanLyBaoMau frmquanlybaomau = new FrmQuanLyBaoMau();
    frmquanlybaomau.setVisible(true);
}//GEN-LAST:event_menuitemQuanLyBaoMauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Main(null, null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblOnline;
    private javax.swing.JLabel lblPiconline;
    private javax.swing.JLabel lblWallpaper;
    private javax.swing.JMenu menuAction;
    private javax.swing.JMenu menuAge;
    private javax.swing.JMenu menuChild;
    private javax.swing.JMenu menuClass;
    private javax.swing.JMenuItem menuDangNhap;
    private javax.swing.JMenuItem menuDangXuat;
    private javax.swing.JMenu menuNanny;
    private javax.swing.JMenuItem menuQuanLyTaiKhoan;
    private javax.swing.JMenuItem menuThoat;
    private javax.swing.JMenu menuUser;
    private javax.swing.JMenuItem menuitemAddActive;
    private javax.swing.JMenuItem menuitemAddClass;
    private javax.swing.JMenuItem menuitemAddchild;
    private javax.swing.JMenuItem menuitemDeleteActive;
    private javax.swing.JMenuItem menuitemDeleteClass;
    private javax.swing.JMenuItem menuitemEditActive;
    private javax.swing.JMenuItem menuitemEditClass;
    private javax.swing.JMenuItem menuitemQuanLyBaoMau;
    private javax.swing.JMenuItem menuitemShowActive;
    private javax.swing.JMenuItem menuitemShowClass;
    // End of variables declaration//GEN-END:variables
}
