/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main.java
 *
 * Created on Nov 19, 2011, 7:27:18 AM
 */
package GUI;

/**
 *
 * @author Administrator
 */
public class Main extends javax.swing.JFrame {
    private String username;
    private String password;

    
    /** Creates new form Main */
    public Main(String username, String password) {
        this.username = username;
        this.password = password;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuUser = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuitemLogin = new javax.swing.JMenuItem();
        menuitemLogout = new javax.swing.JMenuItem();
        menuitemExit = new javax.swing.JMenuItem();
        menuChild = new javax.swing.JMenu();
        menuitemAddchild = new javax.swing.JMenuItem();
        menuEditChild = new javax.swing.JMenuItem();
        menuDeleteChild = new javax.swing.JMenuItem();
        menuitemShowChild = new javax.swing.JMenuItem();
        menuNanny = new javax.swing.JMenu();
        menuitemNanny = new javax.swing.JMenuItem();
        menuitemEditNanny = new javax.swing.JMenuItem();
        menuitemDeleteNanny = new javax.swing.JMenuItem();
        menuitemShowNanny = new javax.swing.JMenuItem();
        menuClass = new javax.swing.JMenu();
        menuitemAddClass = new javax.swing.JMenuItem();
        menuitemEditClass = new javax.swing.JMenuItem();
        menuitemDeleteClass = new javax.swing.JMenuItem();
        menuitemShowClass = new javax.swing.JMenuItem();
        menuAge = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        menuAction = new javax.swing.JMenu();
        menuitemAddActive = new javax.swing.JMenuItem();
        menuitemEditActive = new javax.swing.JMenuItem();
        menuitemDeleteActive = new javax.swing.JMenuItem();
        menuitemShowActive = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/User.png"))); // NOI18N
        menuUser.setText("Quản lý người dùng");

        jMenuItem1.setText("Quản lý tài khoản");
        menuUser.add(jMenuItem1);

        menuitemLogin.setText("Đăng nhập");
        menuUser.add(menuitemLogin);

        menuitemLogout.setText("Đăng xuất");
        menuUser.add(menuitemLogout);

        menuitemExit.setText("Thoát");
        menuUser.add(menuitemExit);

        jMenuBar1.add(menuUser);

        menuChild.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.png"))); // NOI18N
        menuChild.setText("Quản lý trẻ");

        menuitemAddchild.setText("Thêm trẻ");
        menuChild.add(menuitemAddchild);

        menuEditChild.setText("Sửa thông tin trẻ");
        menuChild.add(menuEditChild);

        menuDeleteChild.setText("Xóa trẻ");
        menuChild.add(menuDeleteChild);

        menuitemShowChild.setText("Hiển thị thông tin về trẻ");
        menuChild.add(menuitemShowChild);

        jMenuBar1.add(menuChild);

        menuNanny.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nanny.png"))); // NOI18N
        menuNanny.setText("Quản lý bảo mẫu");

        menuitemNanny.setText("Thêm bảo mẫu");
        menuNanny.add(menuitemNanny);

        menuitemEditNanny.setText("Sửa thông tin bảo mẫu");
        menuNanny.add(menuitemEditNanny);

        menuitemDeleteNanny.setText("Xóa bảo mẫu");
        menuNanny.add(menuitemDeleteNanny);

        menuitemShowNanny.setText("Hiển thị thông tin bảo mẫu");
        menuNanny.add(menuitemShowNanny);

        jMenuBar1.add(menuNanny);

        menuClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Class.png"))); // NOI18N
        menuClass.setText("Quản lý lớp");

        menuitemAddClass.setText("Thêm lớp học");
        menuClass.add(menuitemAddClass);

        menuitemEditClass.setText("Sửa thông tin lớp học");
        menuClass.add(menuitemEditClass);

        menuitemDeleteClass.setText("Xóa lớp học");
        menuClass.add(menuitemDeleteClass);

        menuitemShowClass.setText("Hiển thị thông tin");
        menuClass.add(menuitemShowClass);

        jMenuBar1.add(menuClass);

        menuAge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.png"))); // NOI18N
        menuAge.setText("Quản lý độ tuổi");
        menuAge.add(jMenuItem11);

        jMenuItem12.setText("jMenuItem12");
        menuAge.add(jMenuItem12);

        jMenuItem13.setText("jMenuItem13");
        menuAge.add(jMenuItem13);

        jMenuItem14.setText("jMenuItem14");
        menuAge.add(jMenuItem14);

        jMenuBar1.add(menuAge);

        menuAction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Modify.png"))); // NOI18N
        menuAction.setText("Quản lý hoạt động của trẻ");

        menuitemAddActive.setText("Thêm hoạt động");
        menuAction.add(menuitemAddActive);

        menuitemEditActive.setText("Sửa thông tin các hoạt động");
        menuAction.add(menuitemEditActive);

        menuitemDeleteActive.setText("Xóa thông tin hoạt động");
        menuAction.add(menuitemDeleteActive);

        menuitemShowActive.setText("Hiển thị thông tin hoạt động");
        menuAction.add(menuitemShowActive);

        jMenuBar1.add(menuAction);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-806)/2, (screenSize.height-459)/2, 806, 459);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Main(null,null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenu menuAction;
    private javax.swing.JMenu menuAge;
    private javax.swing.JMenu menuChild;
    private javax.swing.JMenu menuClass;
    private javax.swing.JMenuItem menuDeleteChild;
    private javax.swing.JMenuItem menuEditChild;
    private javax.swing.JMenu menuNanny;
    private javax.swing.JMenu menuUser;
    private javax.swing.JMenuItem menuitemAddActive;
    private javax.swing.JMenuItem menuitemAddClass;
    private javax.swing.JMenuItem menuitemAddchild;
    private javax.swing.JMenuItem menuitemDeleteActive;
    private javax.swing.JMenuItem menuitemDeleteClass;
    private javax.swing.JMenuItem menuitemDeleteNanny;
    private javax.swing.JMenuItem menuitemEditActive;
    private javax.swing.JMenuItem menuitemEditClass;
    private javax.swing.JMenuItem menuitemEditNanny;
    private javax.swing.JMenuItem menuitemExit;
    private javax.swing.JMenuItem menuitemLogin;
    private javax.swing.JMenuItem menuitemLogout;
    private javax.swing.JMenuItem menuitemNanny;
    private javax.swing.JMenuItem menuitemShowActive;
    private javax.swing.JMenuItem menuitemShowChild;
    private javax.swing.JMenuItem menuitemShowClass;
    private javax.swing.JMenuItem menuitemShowNanny;
    // End of variables declaration//GEN-END:variables
}
