/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main.java
 *
 * Created on Nov 19, 2011, 7:27:18 AM
 */
package GUI;
import DAO.Connect;
import DatabaseAccess.quanLyTre;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.beans.PropertyVetoException;
import java.io.InputStream;
import javax.swing.JFrame;
import java.sql.*;
import java.util.*;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Administrator
 */
public class Main extends javax.swing.JFrame {
    private String username;
    private String password;
DefaultTableModel model;
    Connection conn;
    Statement st;
    PreparedStatement pstmt;
    ResultSet rs;
    quanLyTre nhap = new quanLyTre();
    Connect connect = new Connect();
    public static  String ChildIDR;
    String conStr = "jdbc:sqlserver://localhost;databaseName=ChildCare";
    String userName = "sa";
    String passWord = "123456";
    
    /** Creates new form Main */
    public Main(String username, String password) {
        this.username = username;
        this.password = password;
        initComponents();
    }
public void logOff(){
    menuQuanLyTaiKhoan.setEnabled(false);
        menuChild.setEnabled(false);
        menuClass.setEnabled(false);
        menuNanny.setEnabled(false);
        menuAction.setEnabled(false);
        menuAge.setEnabled(false);
}
public static Connection conn() throws SQLException, ClassNotFoundException{
    String conStr = "jdbc:sqlserver://localhost;databaseName=ChildCare";
    String userName = "sa";
    String passWord = "123456";
    Connection conn=null;
    try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection(conStr, userName, passWord); 
    }
    catch(SQLException sql){
        System.out.println(sql.getMessage());
    }
    return conn;
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuUser = new javax.swing.JMenu();
        menuQuanLyTaiKhoan = new javax.swing.JMenuItem();
        menuDangNhap = new javax.swing.JMenuItem();
        menuDangXuat = new javax.swing.JMenuItem();
        menuThoat = new javax.swing.JMenuItem();
        menuChild = new javax.swing.JMenu();
        menuQuanLyTre = new javax.swing.JMenuItem();
        menuThongKeDanhSach = new javax.swing.JMenuItem();
        menuNanny = new javax.swing.JMenu();
        menuitemNanny = new javax.swing.JMenuItem();
        menuitemEditNanny = new javax.swing.JMenuItem();
        menuitemDeleteNanny = new javax.swing.JMenuItem();
        menuitemShowNanny = new javax.swing.JMenuItem();
        menuClass = new javax.swing.JMenu();
        menuitemAddClass = new javax.swing.JMenuItem();
        menuitemEditClass = new javax.swing.JMenuItem();
        menuitemDeleteClass = new javax.swing.JMenuItem();
        menuitemShowClass = new javax.swing.JMenuItem();
        menuAge = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        menuAction = new javax.swing.JMenu();
        menuitemAddActive = new javax.swing.JMenuItem();
        menuitemEditActive = new javax.swing.JMenuItem();
        menuitemDeleteActive = new javax.swing.JMenuItem();
        menuitemShowActive = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Main");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );

        menuUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/User.png"))); // NOI18N
        menuUser.setText("Quản lý người dùng");

        menuQuanLyTaiKhoan.setText("Quản lý tài khoản");
        menuQuanLyTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyTaiKhoanActionPerformed(evt);
            }
        });
        menuUser.add(menuQuanLyTaiKhoan);

        menuDangNhap.setText("Đăng nhập");
        menuDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDangNhapActionPerformed(evt);
            }
        });
        menuUser.add(menuDangNhap);

        menuDangXuat.setText("Đăng xuất");
        menuDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDangXuatActionPerformed(evt);
            }
        });
        menuUser.add(menuDangXuat);

        menuThoat.setText("Thoát");
        menuThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThoatActionPerformed(evt);
            }
        });
        menuUser.add(menuThoat);

        jMenuBar1.add(menuUser);

        menuChild.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.png"))); // NOI18N
        menuChild.setText("Quản lý trẻ");

        menuQuanLyTre.setText("Quản lý trẻ");
        menuQuanLyTre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyTreActionPerformed(evt);
            }
        });
        menuChild.add(menuQuanLyTre);

        menuThongKeDanhSach.setText("Thống kê danh sách");
        menuThongKeDanhSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThongKeDanhSachActionPerformed(evt);
            }
        });
        menuChild.add(menuThongKeDanhSach);

        jMenuBar1.add(menuChild);

        menuNanny.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nanny.png"))); // NOI18N
        menuNanny.setText("Quản lý bảo mẫu");

        menuitemNanny.setText("Thêm bảo mẫu");
        menuNanny.add(menuitemNanny);

        menuitemEditNanny.setText("Sửa thông tin bảo mẫu");
        menuNanny.add(menuitemEditNanny);

        menuitemDeleteNanny.setText("Xóa bảo mẫu");
        menuNanny.add(menuitemDeleteNanny);

        menuitemShowNanny.setText("Hiển thị thông tin bảo mẫu");
        menuNanny.add(menuitemShowNanny);

        jMenuBar1.add(menuNanny);

        menuClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Class.png"))); // NOI18N
        menuClass.setText("Quản lý lớp");

        menuitemAddClass.setText("Thêm lớp học");
        menuClass.add(menuitemAddClass);

        menuitemEditClass.setText("Sửa thông tin lớp học");
        menuClass.add(menuitemEditClass);

        menuitemDeleteClass.setText("Xóa lớp học");
        menuClass.add(menuitemDeleteClass);

        menuitemShowClass.setText("Hiển thị thông tin");
        menuClass.add(menuitemShowClass);

        jMenuBar1.add(menuClass);

        menuAge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.png"))); // NOI18N
        menuAge.setText("Quản lý độ tuổi");
        menuAge.add(jMenuItem11);

        jMenuItem12.setText("jMenuItem12");
        menuAge.add(jMenuItem12);

        jMenuItem13.setText("jMenuItem13");
        menuAge.add(jMenuItem13);

        jMenuItem14.setText("jMenuItem14");
        menuAge.add(jMenuItem14);

        jMenuBar1.add(menuAge);

        menuAction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Modify.png"))); // NOI18N
        menuAction.setText("Quản lý hoạt động của trẻ");

        menuitemAddActive.setText("Thêm hoạt động");
        menuAction.add(menuitemAddActive);

        menuitemEditActive.setText("Sửa thông tin các hoạt động");
        menuAction.add(menuitemEditActive);

        menuitemDeleteActive.setText("Xóa thông tin hoạt động");
        menuAction.add(menuitemDeleteActive);

        menuitemShowActive.setText("Hiển thị thông tin hoạt động");
        menuAction.add(menuitemShowActive);

        jMenuBar1.add(menuAction);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-806)/2, (screenSize.height-459)/2, 806, 459);
    }// </editor-fold>//GEN-END:initComponents

    private void menuQuanLyTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyTaiKhoanActionPerformed
        // TODO add your handling code here:
        FrmManagementUser frmquanlytaikhoan = new FrmManagementUser();
        frmquanlytaikhoan.setVisible(true);
        
    }//GEN-LAST:event_menuQuanLyTaiKhoanActionPerformed

    private void menuDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDangXuatActionPerformed
        // TODO add your handling code here:
        logOff();
        
    }//GEN-LAST:event_menuDangXuatActionPerformed

    private void menuThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuThoatActionPerformed

    private void menuDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDangNhapActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_menuDangNhapActionPerformed

    private void menuQuanLyTreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyTreActionPerformed
        // TODO add your handling code here:
        FrmManagementChild frmquanlytre = new FrmManagementChild();
        frmquanlytre.setVisible(true);
    }//GEN-LAST:event_menuQuanLyTreActionPerformed

    private void menuThongKeDanhSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThongKeDanhSachActionPerformed
        // TODO add your handling code here:
           
        try {
 //           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
 //           conn = DriverManager.getConnection(conStr, userName, passWord);  
            String name="E:/PHAMNGOCVIET/JAVA/doancongnghephanmem/ChildCare/src/Report/report2.jrxml";
            HashMap hm=new HashMap();// sao cua cau lai bao loi thu vien :(
            InputStream is = this.getClass().getClassLoader().getResourceAsStream(name);//mang nha cau cham ag :-d
            //ua sao bao sai nhi cau viet trong project nao doi to xem lai da. uh.o may to van chay nhu thuong, sao qua may cau lam the lai khong duoc.no bao cac ham trong thu vien inputstream loi va thieu
           // JasperReport jr = JasperCompileManager.compileReport("E:/PHAMNGOCVIET/JAVA/doancongnghephanmem/ChildCare/src/Report/report2.jrxml");
            JasperPrint jp = JasperFillManager.fillReport(is, hm, conn());//cau thu add lai thu vien xem, con dau to va cau lam khong sai dau
            JasperViewer viewer = new JasperViewer(jp,false);
            //viewer.setOpaque(true);// to' co' cai' report2.jrxml roi` bay h to' muon' cau. code cai' nay` de? goi. duoc cai' day'
            //to dung inputstream uh the' cau. sua? theo cach' cua? cau. di sao ko thay' gi` nhi?
            //da goi chua cau goi di set vis la ok
           
            viewer.setVisible(true);//to khong lam theo the nay
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_menuThongKeDanhSachActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Main(null,null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuAction;
    private javax.swing.JMenu menuAge;
    private javax.swing.JMenu menuChild;
    private javax.swing.JMenu menuClass;
    private javax.swing.JMenuItem menuDangNhap;
    private javax.swing.JMenuItem menuDangXuat;
    private javax.swing.JMenu menuNanny;
    private javax.swing.JMenuItem menuQuanLyTaiKhoan;
    private javax.swing.JMenuItem menuQuanLyTre;
    private javax.swing.JMenuItem menuThoat;
    private javax.swing.JMenuItem menuThongKeDanhSach;
    private javax.swing.JMenu menuUser;
    private javax.swing.JMenuItem menuitemAddActive;
    private javax.swing.JMenuItem menuitemAddClass;
    private javax.swing.JMenuItem menuitemDeleteActive;
    private javax.swing.JMenuItem menuitemDeleteClass;
    private javax.swing.JMenuItem menuitemDeleteNanny;
    private javax.swing.JMenuItem menuitemEditActive;
    private javax.swing.JMenuItem menuitemEditClass;
    private javax.swing.JMenuItem menuitemEditNanny;
    private javax.swing.JMenuItem menuitemNanny;
    private javax.swing.JMenuItem menuitemShowActive;
    private javax.swing.JMenuItem menuitemShowClass;
    private javax.swing.JMenuItem menuitemShowNanny;
    // End of variables declaration//GEN-END:variables
}
